# Portage options ----------------------------------------------

FEATURES="buildpkg parallel-fetch parallel-install"
EMERGE_DEFAULT_OPTS="-tv -j3 --keep-going"

GENTOO_MIRRORS="https://ftp.jaist.ac.jp/pub/Linux/Gentoo/ https://distfiles.gentoo.org"
FETCHCOMMAND="${FETCHCOMMAND} -t3 -T3"
RESUMECOMMAND="${RESUMECOMMAND} -t3 -T3"

PORTAGE_WORKDIR_MODE=0770
#ECLASS_DEBUG_OUTPUT=on

# Compiler options ---------------------------------------------

CPU=native

CFLAGS="-march=$CPU -O2 -pipe"
CXXFLAGS="${CFLAGS}"
FCFLAGS="${CFLAGS}"
FFLAGS="${CFLAGS}"

RUSTFLAGS="-Copt-level=2 -Ctarget-cpu=$CPU"

DMDFLAGS="-mcpu=$CPU -O"
GDCFLAGS="${CFLAGS} -frelease"
LDCFLAGS="-march=$CPU -O2 -release"

# Packages options ---------------------------------------------

ACCEPT_KEYWORDS="~amd64"
ACCEPT_LICENSE="* -@EULA"

# basic
USE="branding btrfs cjk crypt flatpak fuse libedit man offensive symlink"
# gui
USE="${USE} X pipewire pulseaudio vaapi vulkan wayland"
# libs
USE="${USE} curl ffmpeg fftw lame llvm lua mpg123 openmp twolame"
# formats
USE="${USE} avif heif jpeg2k jpegxl ldac lz4 lzma lzo opus raw sixel vpx webp x265 xpm woff2 zstd"
# optimize
USE="${USE} asm jemalloc lto pgo system-bootstrap system-llvm"
# devices
USE="${USE} bluetooth bluray cdr dvd tpm"
# nvidia
#USE="${USE} cuda nvdec nvenc vdpau"

L10N="ja"

#CPU_FLAGS_X86=""

# https://wiki.gentoo.org/wiki/AMDGPU#Feature_support
# https://wiki.gentoo.org/wiki/Radeon#Feature_support
#VIDEO_CARDS="amdgpu radeonsi"
# https://wiki.gentoo.org/wiki/NVIDIA#Feature_support
#VIDEO_CARDS="nouveau nvidia"
# https://wiki.gentoo.org/wiki/Intel#Feature_support
#VIDEO_CARDS="intel"
